### PR TITLE
fix #60 - adding in GA snippet

### LINKED ISSUE #60: Add in Google Analytics snippet
Have been provided with a GA snippet to use - feels like a good thing to include it in.

### PR DESCRIPTION
**Pull request by rossbruniges**

### CODE REVIEW

**Comment by rossbruniges** [comment]
One thing I'm not sure if it's possible to do but would be nice to be able to only add this code to visitors on production site.

Are there suitable flags in the app for us to do that?

**Comment by stenington** [comment]
Accepting this, and then will add on something that should limit it to production.

**Comment by rossbruniges** [comment]
Are you able to chuck a flag into settings_local and then have something expose that flag to the templates - that's what I use on my apps...

**Comment by stenington** [comment]
Sort of... this site uses the same thing as hackasaurus.org, which actually has a build step to build a static site. So instead of having different `settings_local` files, I've added a `--production` flag to the build step that sets a variable for the templates. #64 if you're curious for more.

**Comment by rossbruniges** [comment]
Ah cool - I was wondering where that kinda stuff was hidden away

**Pull request merged**
