### PR TITLE
Removed unused html-elements for IE

### PR DESCRIPTION
**Pull request by icaaq**
.bad-ie is never used in the css. No need to add these conditional comments if they are not used.

If this pull request will be denied you will need to fix the conditional comments anyway, because the way it's implemented right now non-ie browsers will not get a html element.

The correct way of implementing a CC like you want it is: :)

```
<!--[if lt IE 9]><html class="no-js bad-ie" lang="en-US" dir="ltr"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en-US" dir="ltr"><!--<![endif]-->
```

### CODE REVIEW

**Comment by brianloveswords** [comment]
My preference would be to keep the Internet Explorer specific classes on the HTML element and to implement it how h5bp does it: https://github.com/h5bp/html5-boilerplate/blob/master/index.html.

It's inevitable that we'll have to implement some CSS hack to fix some version of Internet Explorer -- the reason we haven't yet is more than likely because we haven't been diligently testing in IE. I'm totally cool with transmitting a handful of extra bytes for something I'm confident we'll use in the future.

What do you think @stenington?

**Comment by icaaq** [comment]
I would say add them if they are necessary :) and you might want to consider a safe css hack instead mathiasbynens.be/notes/safe-css-hacks

**Comment by brianloveswords** [comment]
I'm definitely opposed to CSS hacks, safe or otherwise. Without comments in the CSS, it requires knowing that `*property: value;` is for <=IE7 and `_property: value;` is for <=IE6. Selecting on ie-specific classes is self-documenting.

**Comment by icaaq** [comment]
Even when it's named .bad-ie ;) 

Anywho, I think one shouldn't fix a problem until one have a problem. Remove them and only add them if you get a problem.

**Comment by stenington** [comment]
Those lines came for free from the [mofodev-template](https://github.com/rossbruniges/mofodev-template), so if there's a problem with them it should definitely be reported there as well. @icaaq can i ask you to file a bug there? 

Of course that doesn't mean we don't need to do something about it here... I agree that we shouldn't fix problems we don't have, although in this case I think we're getting ready to fix a problem we're pretty sure we're about to have. 

I'm thinking we accept this pull and spin off an issue to bring in the h5bp style solution @brianloveswords suggests, preferably with some actual IE  testing at that time. In fact, that's what I'll go ahead and do!

**Pull request merged**
